Brother\GuestbookBundle\Entity\Entry:
    table: brother_guestbook
    type: entity
    indexes:
        created_at_idx:
            columns:
                - created_at
        name_idx:
            columns:
                - name
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
            nullable: true
        profession:
            type: string
            length: 100
            nullable: true
        email:
            type: string
            length: 100
            nullable: false
        comment:
            type: text
        state:
            type: boolean
        replied:
            type: boolean
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        replied_at:
            type: datetime
            nullable: true
    lifecycleCallbacks:
        prePersist: [ prePersist ]
        preUpdate:  [ preUpdate ]
