parameters:
    brother_guestbook.view.mail.notify: 'BrotherQuestBundle:Mail:notify.txt.twig'
    brother_guestbook.mailer.config:
        notification:
            title: %brother_guestbook.mailer.email_title%
            from: %brother_guestbook.mailer.sender_email%
            to: %brother_guestbook.mailer.admin_email%
            view: %brother_guestbook.view.mail.notify%
services:

    brother_guestbook.pager.default:
        class: %brother_guestbook.pager.class%

    brother_guestbook.mailer:
        class: %brother_guestbook.mailer.class%
        arguments:
            - '@event_dispatcher'
            - '@mailer'
            - '@templating'
            - %brother_guestbook.mailer.config%

    brother_guestbook.admin.entry:
        class: Brother\GuestbookBundle\Admin\EntryAdmin
        arguments: [~, Brother\GuestbookBundle\Entity\Entry, BrotherGuestbookBundle:EntryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Guestbook }
