<?php

namespace Brother\GuestbookBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class EntryAdmin extends Admin
{
    public function __construct($code, $class, $baseControllerName)
    {
        parent::__construct($code, $class, $baseControllerName); // TODO: Change the autogenerated stub
        $this->setTranslationDomain('BrotherGuestbookBundle');
    }


    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')
            ->add('name')
            ->add('email')
            ->add('comment')
            ->add('state')
            ->add('replied')
            ->add('created_at')
            ->add('updated_at')
            ->add('replied_at')
        ;
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('id')
            ->add('user')
            ->add('name', null, array('editable' => true))
            ->add('profession')
            ->add('email')
            ->add('announce')
            ->add('state', null, array('editable' => true))
            ->add('replied', null, array('editable' => true))
            ->add('created_at')
            ->add('replied_at')
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                    'delete' => array(),
                )
            ))
        ;
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('Personal', array('class' => 'col-md-6'))
            ->add('user')
            ->add('name')
            ->add('profession')
            ->add('email')
            ->end()
            ->with('Other', array('class' => 'col-md-6'))
            ->add('comment', 'textarea', array(
                'attr' => array(
                    'class' => 'span10',
                    'rows' => 12
                ),
                'horizontal_input_wrapper_class' => $this->getConfigurationPool()->getOption('form_type') == 'horizontal' ? 'col-lg-12' : '',
            ))

            ->add('state')
            ->add('replied')

            ->end()
        ;
    }

    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->with('Personal', array('class' => 'col-md-4'))
            ->add('id')
            ->add('user')
            ->add('name')
            ->add('profession')
            ->add('email')
            ->end()
            ->with('Other', array('class' => 'col-md-8'))
            ->add('comment')
            ->add('state')
            ->add('replied')
            ->add('created_at')
            ->add('updated_at')
            ->add('replied_at')
            ->end()
        ;
    }
}
